version: "3.2"
services:
  nuxt-primevue:
    user: developer
    container_name: nuxt-primevue
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - type: bind
        source: ${HOME}${USERPROFILE}/.ssh
        target: /home/developer/.ssh
      - notused:/opt/app/node_modules
    working_dir: /workspace
    command: sleep infinity
    environment:
      # BUNDLE_PATH: vendor/bundle
      INTERFACE: "0.0.0.0"
    ports:
      - "3080:3080"
      - "9229:9229"
      - "9230:9230"
  volumes:
    notused:
