version: "3.2"
services:
  nuxt-primevue:
    user: node
    container_name: nuxt-primevue
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
      # - type: bind
      #   source: ${HOME}${USERPROFILE}/.ssh
      #   target: /home/node/.ssh
    working_dir: /workspace
    command: yarn run dev
    environment:
      # BUNDLE_PATH: vendor/bundle
      INTERFACE: "0.0.0.0"
    ports:
      - "3080:3080"
      - "9229:9229"
      - "9230:9230"
